CRM/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('home/',include('home.urls'))
]

home/urls.py
from django.urls import path
from . import views
app_name = "home_app"
urlpatterns = [
    path("",views.home,name='home'),
    path('create-agent/',views.create_agent,name="create_agent"),
    path('delete-agent/', views.delete_agent, name='delete_agent'),
    path('update-agent/', views.update_agent, name='update_agent'),
]

login/urls.py
from django.urls import path
from . import views
app_name="login"
urlpatterns = [
    path("",views.login_user,name='login'),
    path("logout/",views.logout_user,name='logout'),
]

home/models.py
from django.db import models
from login.models import BaseModel
from django.core.validators import  MinValueValidator 
from login.models import Role

class Agents(BaseModel):
    first_name=models.fields.CharField(max_length=50,blank=False,null=False)
    last_name=models.fields.CharField(max_length=50,blank=False,null=False)
    country=models.fields.CharField(max_length=50,blank=False,null=False)
    age=models.fields.IntegerField(validators=[MinValueValidator(18)])
    balance=models.fields.FloatField(validators=[MinValueValidator(0)])

    role=models.OneToOneField(Role, verbose_name="user_role", on_delete=models.CASCADE)

login/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_current_user
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class BaseModel(models.Model):
    id=models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated at')
    created_by = models.ForeignKey(
        User,
        null=True,
        editable=False,
        related_name="%(class)s_created",
        on_delete=models.DO_NOTHING,
        verbose_name='Created by'
    )
    updated_by = models.ForeignKey(
        User,
        null=True,
        editable=False,
        related_name="%(class)s_updated",
        on_delete=models.DO_NOTHING,
        verbose_name='Updated by'
    )
    class Meta:
        abstract = True
    def save(self, *args, **kwargs):
        user = get_current_user()
        if user:
            self.updated_by = user
            if not self.id:
                self.created_by = user
        super(BaseModel, self).save(*args, **kwargs)
    
class Role(models.Model):
    ROLE_CHOICES = [
        ('Admin', 'Admin'),
        ('Support', 'Support'),
        ('Developer', 'Developer'),
        ('OnlyAgent', 'OnlyAgent'),
    ]
    type = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
        default='OnlyAgent')
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='user',
        null=True
    )

home/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import JsonResponse
from .models import Agents
from login.models import Role
from .permissions import has_edit_perm,has_create_perm,has_delete_perm,has_view_perm
import json


@has_view_perm    
def home(request):
    if hasattr(request.user, 'role'):
        user_role = request.user.role.type
    elif request.user.is_staff:
         user_role='Admin'
    if request.method == "GET":
        agents = Agents.objects.all().order_by('id')
        role_choices = Role.ROLE_CHOICES
    return render(request, "home.html", {"pagename": "home", 'agents': agents, 'role_choices': role_choices,'user_role':user_role})

@has_create_perm
def create_agent(request):
    if request.method == "POST":
        data = json.loads(request.body.decode('UTF-8')).get('data')
        try:
            role = Role(type=data.get('role'))
            if data.get('role') != 'OnlyAgent':
                user=User(username=data.get('first_name')+'.'+data.get('last_name'),password=data.get('password'))
                user.set_password(user.password)
                user.save()
                role.user=user
            role.save()
            agent = Agents(first_name=data.get('first_name'), last_name=data.get('last_name'), role=role, country=data.get('country'), age=data.get('age'), balance=data.get('balance'))
            agent.save()
            return JsonResponse({'Success': True, 'ID': agent.id})
        except Exception as e:
            return JsonResponse({'Success': False, 'error': str(e)})
    else:
        return JsonResponse({'Success': False, 'error': 'Method not allowed'}, status=405)
    
@has_delete_perm
def delete_agent(request):
    if request.method == 'DELETE':
        data = json.loads(request.body.decode('UTF-8')).get('data')
        try:
            Agents.objects.get(id=data).delete()
            return JsonResponse({'Success': True, 'ID': data})
        except Exception as e:
            return JsonResponse({'Success': False, 'error': str(e)})
    else:
        return JsonResponse({'Success': False, 'error': 'Method not allowed'}, status=405)
@has_edit_perm
def update_agent(request):
    if request.method == 'PUT':
        data = json.loads(request.body.decode('UTF-8')).get('data')
        agent = Agents.objects.get(id=data.get('id'))
        del data['id']
        for key, value in data.items():
            if key=='role':
                agent.role.type=data.get('role')
                agent.role.save()
            else:
                setattr(agent, key, value)
        agent.save()
        return JsonResponse({'Success': True})
    else:
        return JsonResponse({'Success': False, 'error': 'Method not allowed'}, status=405)

        

login/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User

def login_user(request):
    if request.method=='GET':
        return render(request,"login.html",{"pagename":"loginpage"})
    elif request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse("home_app:home"))
        else:
            return render(request, "login.html", {"pagename": "loginpage","Error_message":"Invalid username or password"})


def logout_user(request):
    logout(request)
    return redirect(reverse('login:login'))
    
    # elif request.method=='POST':
    #     username = request.POST.get('username')
    #     password = request.POST.get('password')
    #     try:
    #         user = User.objects.get(username=username)
    #         if check_password(password, user.password):
    #             request.session['user'] = user.id
    #             return redirect('/home')
    #         else:
    #             raise User.DoesNotExist
    #     except User.DoesNotExist:
    #         return render(request, "login.html", {"pagename": "loginpage","Error_message":"Invalid username or password"})


        

templates/home.html
{% load static %}
{% block head %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    {% comment %} 
    <!-- Bootstrap icons-->
    
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" /> {% endcomment %}
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static "css/homestyle.css" %}">

    <script>
        var imagePath = "{% static 'assets/images.png' %}";
        var csrf_token = "{{ csrf_token }}";
        var role="{{user_role}}"
    </script>

</head>
{% endblock head %}
{% block body %}
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" >CRM  <span class="badge bg-dark text-white ms-1 rounded-pill">{{request.user.username}}</span><span class="badge bg-danger text-white ms-1 rounded-pill">{{user_role}}</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page">Agents</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Search</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><input type="text" name="searchAgent" placeholder="Search for agents"/></li>
                      <li><hr class="dropdown-divider" /></li>
                      <li><a class="dropdown-item" onclick="toggleSelection(event)">Name</a></li>
                      <li><a class="dropdown-item" onclick="toggleSelection(event)">Role</a></li>
                      <li><a class="dropdown-item" onclick="toggleSelection(event)">Country</a></li>
                      <li><a class="dropdown-item" onclick="toggleSelection(event)">Age</a></li>
                    </ul>
                  </li>
            </ul>
 
           
             <div class="d-flex">
                {% if user_role == 'Admin' or user_role == 'Developer' %}
                <button id="addContainerBtn" class="btn btn-outline-dark" type="submit">
                    <i class="bi bi-person-plus-fill me-1"></i>
                    Add Agent
                </button>
                {% endif %}
                <a href="{% url "login:logout" %}" class="btn btn-outline-dark" type="submit">
                    <i class="bi bi-box-arrow-right"></i>
                    logout
                </a>
                    {% comment %} <span class="badge bg-dark text-white ms-1 rounded-pill">0</span> {% endcomment %}
                </button>
            </div>
           
        </div>
    </div>
</nav>
<!-- Header-->
<!-- Section-->
<section class="py-5">

    <div class="container px-4 px-lg-5 mt-5">
        <div id="AgentsContainers" class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% if not  agents %}
            <img id="emptybox" src="{% static "assets/empty-box-1.png" %}"/>
            {% endif %}
            {% for agent in agents %}
            <div id="AgentContainer{{agent.id}}" class="col mb-5">
                <div class="card h-100">
                    <!-- Role -->
                    {% if user_role == 'Admin' %}
                            <select onchange="rolechange(event)" name="role" class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                {% for value, display in role_choices %}
                                    <option value="{{ value }}" {% if agent.role.type == value %}selected{% endif %}>{{ display }}</option>
                                {% endfor %}
                            </select>
                   {% else %}
                            <span name="role" class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                                {{ agent.role.type }}
                            </span>
                    {% endif %}
                                        
                    <!-- Image -->
                    <img class="card-img-top" src="{% static 'assets/images.png' %}" alt="..." width="450" height="200" />
                    <!-- Details -->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Info -->
                            <h6 class="fw-bolder"><span name="id">ID: {{ agent.id }}</span></h6>
                            <span  class="fw-bolder" {% if user_role == 'Admin' %} contentEditable="true" {% endif %}  name="firstname">{{ agent.first_name }}</span>
                            <span class="fw-bolder" {% if user_role == 'Admin' %} contentEditable="true" {% endif %}  name="lastname">{{ agent.last_name }}</span>
                            <h6><span name="country" class="fw-bolder" {% if user_role == 'Admin' %} contentEditable="true" {% endif %} >{{ agent.country }}</span></h6>
                            <hr/>
                            <strong><span class="balance" {% if user_role == 'Admin' %} contentEditable="true" {% endif %}  name="age">{{ agent.age }} </span><span class="age"> Years</span></strong>
                            <br/>
                            <span class="currency">$</span>
                            <span class="balance" {% if user_role == 'Admin' %} contentEditable="true" {% endif %}   name="balance">{{ agent.balance }}</span>
                        </div>
                    </div>
                    <!-- Product actions -->
                    {% if user_role == 'Admin' %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent" style="display:flex;justify-content: space-between;">
                        <div class="text-center"><button onclick='editAgent(event,{{ agent.id }})' class="btn btn-outline-dark mt-auto">Edit</button></div>
                        <div class="text-center" onclick='deleteAgent({{ agent.id }})'><button class="btn btn-outline-dark mt-auto">Delete</button></div>
                    </div>
                    {% endif %}
                </div>
            </div>
                {% endfor %}
            </div>
    </div>
</section>

<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<!-- Core theme JS-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src=" {% static "js/script.js" %}"></script>
</body>

{% endblock body %}

templates/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static "css/login.scss" %}">

{% block body %}
<body>
  <div class="session">
    <div class="left">
      <?xml version="1.0" encoding="UTF-8"?>
      <svg enable-background="new 0 0 300 302.5" version="1.1" viewBox="0 0 300 302.5" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
        <style type="text/css">
          .st01 { fill: #fff; }
        </style>
        <path class="st01" d="m126 302.2c-2.3 0.7-5.7 0.2-7.7-1.2l-105-71.6c-2-1.3-3.7-4.4-3.9-6.7l-9.4-126.7c-0.2-2.4 1.1-5.6 2.8-7.2l93.2-86.4c1.7-1.6 5.1-2.6 7.4-2.3l125.6 18.9c2.3 0.4 5.2 2.3 6.4 4.4l63.5 110.1c1.2 2 1.4 5.5 0.6 7.7l-46.4 118.3c-0.9 2.2-3.4 4.6-5.7 5.3l-121.4 37.4zm63.4-102.7c2.3-0.7 4.8-3.1 5.7-5.3l19.9-50.8c0.9-2.2 0.6-5.7-0.6-7.7l-27.3-47.3c-1.2-2-4.1-4-6.4-4.4l-53.9-8c-2.3-0.4-5.7 0.7-7.4 2.3l-40 37.1c-1.7 1.6-3 4.9-2.8 7.2l4.1 54.4c0.2 2.4 1.9 5.4 3.9 6.7l45.1 30.8c2 1.3 5.4 1.9 7.7 1.2l52-16.2z"/>
      </svg>
    </div>
    <form action="{% url "login:login" %}" method="POST" class="log-in" autocomplete="off">
        {% csrf_token %}
      <h4><span>CRM</span></h4>
      <p>A Customer Relationship Management website
        <br/>
        <p>You can login with three types of users</p>
        <ul>
            <li>Admin</li>
            <li>Support</li>
            <li>Developer</li>
        </ul>
        
      </p>
            <!-- Display messages here -->
        {% if Error_message %}
        <div class="messages">
            <div class="alert-error">
                {{ Error_message }}
            </div>
        </div>
        {% endif %}
      <div class="floating-label">
        <input required placeholder="Username" type="text" name="username" id="email" autocomplete="off">
        <label for="email">UserName:</label>
        <div class="icon">
          <?xml version="1.0" encoding="UTF-8"?>
          <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" xml:space="preserve">
            <style type="text/css">
              .st0 { fill: none; }
            </style>
            <g transform="translate(0 -952.36)">
              <circle cx="50" cy="976.36" r="10"/>
              <path d="M50,992.36c-13.8,0-25,11.2-25,25h50C75,1003.56,63.8,992.36,50,992.36z"/>
            </g>
            <rect class="st0" width="100" height="100"/>
          </svg>
        </div>
      </div>
      <div class="floating-label">
        <input required placeholder="Password" type="password" name="password" id="password" autocomplete="off">
        <label for="password">Password:</label>
        <div class="icon">
          <?xml version="1.0" encoding="UTF-8"?>
          <svg enable-background="new 0 0 24 24" version="1.1" viewBox="0 0 24 24" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
            <style type="text/css">
              .st0 { fill: none; }
              .st1 { fill: #010101; }
            </style>
            <rect class="st0" width="24" height="24"/>
            <path class="st1" d="M19,21H5V9h14V21z M6,20h12V10H6V20z"/>
            <path class="st1" d="M16.5,10h-1V7c0-1.9-1.6-3.5-3.5-3.5S8.5,5.1,8.5,7v3h-1V7c0-2.5,2-4.5,4.5-4.5s4.5,2,4.5,4.5V10z"/>
            <path class="st1" d="m12 16.5c-0.8 0-1.5-0.7-1.5-1.5s0.7-1.5 1.5-1.5 1.5 0.7 1.5 1.5-0.7 1.5-1.5 1.5zm0-2c-0.3 0-0.5 0.2-0.5 0.5s0.2 0.5 0.5 0.5 0.5-0.2 0.5-0.5-0.2-0.5-0.5-0.5z"/>
          </svg>
        </div>
      </div>
      <button type="submit" >Log in</button>
      <a href="https://codepen.io/elujambio/pen/yjwzGP" class="discrete" target="_blank">Basic version</a>
    </form>
  </div>
</body>
{% endblock body %}
{% load static %}
<script src=" {% static "js/script.js" %}"></script>